$ErrorActionPreference = "Stop"

$repoRoot = git rev-parse --show-toplevel
if (-not $repoRoot) {
    throw "Run this from inside the POC repository."
}

Set-Location $repoRoot

if (-not (Get-Command betterleaks -ErrorAction SilentlyContinue)) {
    throw "betterleaks is not on PATH. Install it before running this POC test."
}

git config core.hooksPath .githooks

$testFile = "tmp-precommit-should-block.env"
@"
# Generated by scripts/test-precommit-block.ps1
internal_service_token=poc_live_blockme0123456789abcdef01234567
"@ | Set-Content -NoNewline -Encoding ascii $testFile

git add $testFile

$beforeCommit = git rev-parse HEAD
Write-Host "Attempting a commit that should be blocked by Betterleaks..."

$previousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$commitOutput = git -c user.name='Betterleaks POC' -c user.email='poc@example.invalid' commit -m "POC should be blocked" 2>&1
$exitCode = $LASTEXITCODE
$ErrorActionPreference = $previousErrorActionPreference

$commitOutput | ForEach-Object { Write-Host $_ }

if ($exitCode -eq 0) {
    git reset --soft $beforeCommit | Out-Null
}

git reset -- $testFile | Out-Null
Remove-Item -LiteralPath $testFile -Force

if ($exitCode -eq 0) {
    throw "Commit succeeded unexpectedly. Check the Betterleaks hook and custom rule config."
}

if ($commitOutput -match "unknown option|failed to scan|error=") {
    throw "Commit was blocked by a Betterleaks/runtime error, not by a detected secret. Review the output above."
}

Write-Host "Success: Betterleaks blocked the staged fake secret."
